# Generated by Django 4.2.1 on 2023-06-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_usuario_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
